---
- name: pkgs installed
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - python*-mysqldb

- name: charset & collation
  copy:
    src: charset-collation.cnf
    dest: /etc/mysql/conf.d
    owner: root
    mode: 0644
  notify:
    - Restart Mysql

- name: user exists
  mysql_user:
    name: "{{ database.creds.user }}"
    password: "{{ database.creds.pass }}"
    priv: "{{ database.name }}.*:ALL"
    state: present

- name: db created
  mysql_db:
    name: "{{ database.name }}"
    collation: utf8_general_ci
    encoding: utf8
    state: present
  register: db_created

- meta: flush_handlers
